# Dependencies
# markdown: redcarpet
markdown: kramdown
highlighter: pygments



# Permalinks
# permalink: pretty
# relative_permalinks: true

# Setup
# title:
# tagline:
# description:
# url:
baseurl: /notes
# paginate:

# Custom vars
# version:

github:
  repo: https://github.com/nltesown/notes/